# Generated by Django 4.2 on 2023-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='musica/img')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
