# Generated by Django 4.2 on 2023-04-19 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escritor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=250)),
                ('poema_text', models.CharField(max_length=5000)),
                ('img', models.ImageField(upload_to='amor/img')),
                ('fecha', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
